# Generated by Django 4.0.3 on 2022-06-02 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=9, unique=True, verbose_name='CIF')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('comision', models.DecimalField(decimal_places=2, default=3, max_digits=4, verbose_name='Comisión')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1ºApellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='2ºApellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1ºApellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='2ºApellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa', verbose_name='Empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1ºApellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='2ºApellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
