# Generated by Django 4.0.3 on 2022-06-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('localizacion', models.CharField(choices=[('01', 'Alaba'), ('02', 'Albacete'), ('03', 'Alicante'), ('04', 'Almería'), ('05', 'Ávila'), ('06', 'Badajoz'), ('07', 'Islas Baleares'), ('08', 'Barcelona'), ('09', 'Burgos'), ('10', 'Cáceres'), ('11', 'Cádiz'), ('12', 'Castellón'), ('13', 'Ciudad Real'), ('14', 'Córdoba'), ('15', 'A Coruña'), ('16', 'Cuenca'), ('17', 'Girona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipúzcoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaén'), ('24', 'León'), ('25', 'Lleida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Málaga'), ('30', 'Murcia'), ('31', 'Navarra'), ('32', 'Ourense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Sevilla'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Vizcaya'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla')], max_length=2, verbose_name='Localización')),
                ('codigo_postal', models.IntegerField(verbose_name='CP')),
                ('metros', models.IntegerField(verbose_name='Metros')),
                ('habitacion', models.CharField(choices=[('0', 'Loft'), ('1', '1 Habitacion'), ('2', '2 Habitaciones'), ('3', '3 Habitaciones'), ('4', '4 Habitaciones'), ('5', '5 Habitaciones'), ('6', 'Más de 5')], max_length=1, verbose_name='Habitación')),
                ('planta', models.IntegerField(verbose_name='Planta')),
                ('wc', models.IntegerField(verbose_name='Baños')),
                ('orientacion', models.CharField(choices=[('1', '(N) Norte'), ('2', '(NO) Noreste'), ('3', '(E) Este'), ('4', '(SE) Sureste'), ('5', '(S) Sur'), ('6', '(SO) Suroeste'), ('7', '(O) Oeste'), ('8', '(NO) Noroeste')], max_length=1, verbose_name='Orientación')),
                ('construccion', models.IntegerField(verbose_name='Año Construcción')),
                ('comunidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Comunidad')),
                ('ascensor', models.BooleanField(default=False, verbose_name='Ascensor')),
                ('terraza', models.BooleanField(default=False, verbose_name='Terraza')),
                ('patio', models.BooleanField(default=False, verbose_name='Patio')),
                ('observacion', models.CharField(max_length=1024, verbose_name='Observacion')),
                ('imagenPrincipal', models.ImageField(upload_to='imagenes/', verbose_name='ImagenPrincipal')),
                ('imagen1', models.ImageField(blank=True, default='imagenes/pordefecto.png', null=True, upload_to='imagenes/', verbose_name='imagen1')),
                ('imagen2', models.ImageField(blank=True, default='imagenes/pordefecto.png', null=True, upload_to='imagenes/', verbose_name='imagen2')),
                ('imagen3', models.ImageField(blank=True, default='imagenes/pordefecto.png', null=True, upload_to='imagenes/', verbose_name='imagen3')),
                ('imagen4', models.ImageField(blank=True, default='imagenes/pordefecto.png', null=True, upload_to='imagenes/', verbose_name='imagen4')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.propietario', verbose_name='propietario')),
            ],
        ),
    ]
